# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/SpringBoot_MongoDB/Dockerfile'
        repository: $(imagename)
        tags: |
          $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'my_aws_springboot_app'
        regionName: 'eu-north-1'
        imageSource: 'imageid'
        sourceImageId: '$(imagename):$(tag)'
        repositoryName: '$(reponame)'
        pushTag: '$(tag)'
        forceDockerNamingConventions: true
